name: Deploy Static HTML Subdomains

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout branch
      uses: actions/checkout@v3

    - name: Set CNAME dynamically
      id: set-cname
      run: |
        BRANCH=$(echo $GITHUB_REF | sed 's/refs\\/heads\\///')
        if [ "$BRANCH" == "accessoires-de-fitness-pas" ]; then
          echo "::set-output name=cname::accessoires-de-fitness-pas.radiateur-electrique.blog"
        elif [ "$BRANCH" == "abattants-et-lunettes-pour" ]; then
          echo "::set-output name=cname::abattants-et-lunettes-pour.radiateur-electrique.blog"
        fi

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./ # Assurez-vous que les fichiers HTML sont à la racine
        cname: ${{ steps.set-cname.outputs.cname }}
