name: Deploy Subdomains

on:
  push:
    branches:
      - accessoires-de-fitness-pas
      - abattants-et-lunettes-pour

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout branch
      uses: actions/checkout@v3

    - name: Build Project (if required)
      run: |
        npm install # Change this if you don't use npm
        npm run build # Remove if no build process is needed

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build # Change to your output directory
        cname: ${{ steps.set-cname.outputs.cname }}

    - name: Set CNAME dynamically
      id: set-cname
      run: |
        echo "::set-output name=cname::$(echo $GITHUB_REF | sed 's/refs\\/heads\\///').radiateur-electrique.blog"
